name: Run tests

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  submodules: recursive

            - uses: pnpm/action-setup@v4.0.0
              with:
                  version: 8.15.9
                  run_install: true

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "18.x"

            - run: pnpm install
            - run: pnpm run build
            - run: pnpm test
